version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - |
      for dir in dist/*/*; do
        ln -sf $(basename $dir)-v${GORELEASER_CURRENT_TAG} \
               $dir/$(basename $dir)
      done

builds:
  - main: ./cmd/ad-runtime-utils
    binary: "{{ .ProjectName }}-{{ .Version }}"
    ldflags:
      - "-X main.Version=v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{- end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - scripts/**
      - configs/**
      - README.MD

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
