version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/ad-runtime-utils
    binary: "{{ .ProjectName }}-{{ .Version }}"
    ldflags:
      - "-X main.Version=v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{- end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - scripts/**
      - configs/**
      - README.MD

nfpms:
  - id: ad-runtime-utils
    package_name: ad-runtime-utils
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"

    vendor: Arenadata
    homepage: https://github.com/arenadata/ad-runtime-utils
    maintainer: Arenadata Team <team@arenadata.com>
    description: |-
      Arenadata Runtime Utilities - Unified Runtime Environment Manager

      ad-runtime-utils is a comprehensive utility tool designed to provide a unified
      interface for runtime environment management in Arenadata platform deployments.

    license: Apache-2.0

    formats:
      - deb
      - rpm

    provides:
      - bigtop-utils

    replaces:
      - bigtop-utils

    conflicts:
      - bigtop-utils

    contents:
      - src: >-
          ./dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if eq .Arch "amd64" }}_v1{{ else if eq .Arch "arm64" }}_v8.0{{ end }}/{{ .ProjectName }}-{{ .Version }}
        dst: /usr/lib/ad-runtime-utils/bin/ad-runtime-utils
        type: file
        file_info:
          mode: 0755

      - src: ./configs/config.yaml
        dst: /etc/ad-runtime-utils/config.yaml
        type: file
        file_info:
          mode: 0644

      - src: ./scripts/bigtop-detect-javahome
        dst: /usr/lib/bigtop-utils/bigtop-detect-javahome
        type: file
        file_info:
          mode: 0755

      - src: ./scripts/bigtop-detect-javalibs
        dst: /usr/lib/bigtop-utils/bigtop-detect-javalibs
        type: file
        file_info:
          mode: 0755

      - src: ./scripts/bigtop-detect-classpath
        dst: /usr/lib/bigtop-utils/bigtop-detect-classpath
        type: file
        file_info:
          mode: 0755

      - src: ./scripts/bigtop-detect-cacerts
        dst: /usr/lib/bigtop-utils/bigtop-detect-cacerts
        type: file
        file_info:
          mode: 0755

      - src: ./scripts/bigtop-monitor-service
        dst: /usr/lib/bigtop-utils/bigtop-monitor-service
        type: file
        file_info:
          mode: 0755

      - src: ./scripts/bigtop-utils.default
        dst: /etc/default/bigtop-utils
        type: file
        file_info:
          mode: 0644

      - dst: /usr/lib/ad-runtime-utils/bin
        type: dir
        file_info:
          mode: 0755

      - dst: /etc/ad-runtime-utils
        type: dir
        file_info:
          mode: 0755

      - dst: /usr/lib/bigtop-utils
        type: dir
        file_info:
          mode: 0755

      - dst: /etc/default
        type: dir
        file_info:
          mode: 0755

    rpm:
      group: Development/Tools
      packager: Arenadata Team <team@arenadata.com>
      compression: gzip

    deb:
      fields:
        Bugs: https://github.com/arenadata/ad-runtime-utils/issues
        Vcs-Browser: https://github.com/arenadata/ad-runtime-utils
        Vcs-Git: https://github.com/arenadata/ad-runtime-utils.git

      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
