services:
  KAFKA:
    executable: /usr/lib/kafka/bin/kafka-server-start.sh
    executable_args:
      - /usr/lib/kafka/config/server.properties
    runtimes:
      java:
        version: "21"
    env_vars:
      KAFKA_OPTS: "-DZstdTempFolder=/usr/lib/kafka/tmp -Dorg.xerial.snappy.tempdir=/usr/lib/kafka/tmp -Djava.io.tmpdir=/var/tmp"
      LOG_DIR: "/var/log/kafka"
      PID_DIR: "/var/run/kafka"
      JMX_PORT: "9999"
    health_checks:
      - type: port
        params:
          port: 9092
          timeout: 20
          protocol: tcp
      - type: port
        params:
          port: 9093
          timeout: 20
          protocol: tcp
