#!/usr/bin/env bash

if [ -z "$JAVA_HOME" ]; then
  echo "JAVA_HOME must be set before calling bigtop-detect-cacerts" >&2
  exit 1
fi

cacerts_path=$(
  /usr/lib/ad-runtime-utils/bin/ad-runtime-utils \
    --config "/etc/ad-runtime-utils/config.yaml" \
    --service "${ADH_SERVICE_NAME:-}" \
    --runtime java \
    --print-cacerts 2>&1
)
ret=$?

if [ $ret -ne 0 ]; then
  echo "Error detecting cacerts: $cacerts_path" >&2
  exit $ret
fi

echo "$cacerts_path"
